[toolchain]
channel = "stable"
profile = "minimal"
components = ["rustfmt", "clippy", "rustc", "cargo", "rust-analyzer"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-gnu", "wasm32-unknown-unknown"]
